class AppDimens {
  // DURATIONS
  static const DURATION_ANIMATION_DEFAULT_MILLISECONDS = 200;

  // DASHBOARD
  static const DASHBOARD_HEIGHT_MULTIPLIER = 0.3;
  static const DASHBOARD_BOTTOM_BAR_NOTCH_MARGIN = 8.0;
  static const DASHBOARD_BOTTOM_BAR_HEIGHT = 48.0;
  static const DASHBOARD_SPACE_BETWEEN_NAVBAR_AND_CATEGORIES = 10.0;

  // CATEGORIES SCROLLER
  static const CATEGORIES_SCROLLER_HEIGHT_MULTIPLIER = 0.3;
  static const CATEGORIES_SCROLLER_MARGIN = 20.0;
  static const CATEGORIES_SCROLLER_ITEM_PADDING = 12.0;
  static const CATEGORIES_SCROLLER_ITEM_RIGHT_MARGIN = 20.0;
  static const CATEGORIES_SCROLLER_ITEM_WIDTH = 160.0;
  static const CATEGORIES_SCROLLER_ITEM_RADIUS = 20.0;
  static const CATEGORIES_SCROLLER_ITEM_BIG_FONT_SIZE = 22.0;
  static const CATEGORIES_SCROLLER_ITEM_FONT_SIZE = 16.0;
  static const CATEGORIES_SCROLLER_ITEM_SPACE_BETWEEN_TEXTS = 10.0;

  // HARRY POTTER CHARACTERS LIST ITEM
  static const HARRY_POTTER_CHARACTERS_LIST_ITEM_HEIGHT = 150.0;
  static const HARRY_POTTER_CHARACTERS_LIST_ITEM_RADIUS = 20.0;
  static const HARRY_POTTER_CHARACTERS_LIST_ITEM_HORIZONTAL_MARGIN = 20.0;
  static const HARRY_POTTER_CHARACTERS_LIST_ITEM_VERTICAL_MARGIN = 10.0;
  static const HARRY_POTTER_CHARACTERS_LIST_ITEM_HORIZONTAL_PADDING = 20.0;
  static const HARRY_POTTER_CHARACTERS_LIST_ITEM_VERTICAL_PADDING = 10.0;
  static const HARRY_POTTER_CHARACTERS_LIST_ITEM_BLUR_ALPHA = 100;
  static const HARRY_POTTER_CHARACTERS_LIST_ITEM_BLUR_RADIUS = 10.0;
  static const HARRY_POTTER_CHARACTERS_LIST_ITEM_BIG_FONT_SIZE = 20.0;
  static const HARRY_POTTER_CHARACTERS_LIST_ITEM_FONT_SIZE = 14.0;
  static const HARRY_POTTER_CHARACTERS_LIST_ITEM_SPACE_BETWEEN_TITLE_AND_INFO =
      10.0;
  static const HARRY_POTTER_CHARACTERS_LIST_ITEM_IMAGE_WIDTH = 80.0;
  static const HARRY_POTTER_CHARACTERS_LIST_ITEM_IMAGE_HEIGHT = 100.0;
  static const HARRY_POTTER_CHARACTERS_LIST_ITEM_IMAGE_CACHED_HEIGHT = 100;

  // DETAILS
  static const DETAILS_EXPANDED_HEIGHT = 350.0;
  static const DETAILS_ITEM_EXTENT = 100.0;
}
